### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by SeekPoint** [tanmayshankar/RCNN_MDP#1]
envy@ub1404:~/os_pri/github/RCNN_MDP$ ./scripts/VI_RCNN/VI_extended_actions.py data/QMDP_old_trajectories/trial_9_action_reward/action_reward_function.txt data/learnt_models/actual_transition.txt
Traceback (most recent call last):
  File "./scripts/VI_RCNN/VI_extended_actions.py", line 33, in <module>
    initialize()
  File "./scripts/VI_RCNN/VI_extended_actions.py", line 31, in initialize
    create_action_reward()
NameError: global name 'create_action_reward' is not defined
envy@ub1404:~/os_pri/github/RCNN_MDP$

**Comment by tanmayshankar** [comment]
Hi @loveJasmine , I recently overhauled the structure of this package, so a few things may be off. Please update your local repo and try this again, it should work.
